name: software-inventory-collector
base: core20
version: '0.1'
summary: Client for collecting data from charm-inventory-exporter
description: |
  Collector designed to pull data exported by
  https://snapcraft.io/software-inventory-exporter

grade: devel
confinement: strict

apps:
  software-inventory-collector:
    command: bin/software-inventory-collector
    plugs:
      - network

parts:
  software-inventory-collector:
    plugin: python
    source: .
    python-packages:
      - .
